groups:
- name: infrascope-generated-service-alerts
  rules:
  - alert: InfraScopeBackendDown
    expr: max_over_time(up{job="infrascope-backend"}[2m]) == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "API Gateway \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\u0435\
        \u043D"
      description: "Prometheus \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u0441\u043E\
        \u0431\u0440\u0430\u0442\u044C \u043C\u0435\u0442\u0440\u0438\u043A\u0438\
        \ API Gateway \u0431\u043E\u043B\u0435\u0435 2 \u043C\u0438\u043D\u0443\u0442\
        ."
  - alert: InfraScopeDiscoveryServiceDown
    expr: max_over_time(up{job="infrascope-discovery-service"}[2m]) == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Discovery Service \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\
        \u0435\u043D"
      description: "Prometheus \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u0441\u043E\
        \u0431\u0440\u0430\u0442\u044C \u043C\u0435\u0442\u0440\u0438\u043A\u0438\
        \ Discovery Service \u0431\u043E\u043B\u0435\u0435 2 \u043C\u0438\u043D\u0443\
        \u0442."
  - alert: InfraScopeMlServiceDown
    expr: max_over_time(up{job="infrascope-ml-service"}[2m]) == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "ML Service \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\u0435\u043D"
      description: "Prometheus \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u0441\u043E\
        \u0431\u0440\u0430\u0442\u044C \u043C\u0435\u0442\u0440\u0438\u043A\u0438\
        \ ML Service \u0431\u043E\u043B\u0435\u0435 2 \u043C\u0438\u043D\u0443\u0442\
        ."
  - alert: InfraScopeNetworkControlServiceDown
    expr: max_over_time(up{job="infrascope-network-control-service"}[2m]) == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Network Control Service \u043D\u0435\u0434\u043E\u0441\u0442\u0443\
        \u043F\u0435\u043D"
      description: "Prometheus \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u0441\u043E\
        \u0431\u0440\u0430\u0442\u044C \u043C\u0435\u0442\u0440\u0438\u043A\u0438\
        \ Network Control Service \u0431\u043E\u043B\u0435\u0435 2 \u043C\u0438\u043D\
        \u0443\u0442."
  - alert: InfraScopePollingServiceDown
    expr: max_over_time(up{job="infrascope-polling-service"}[2m]) == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Polling Service \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\u0435\
        \u043D"
      description: "Prometheus \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u0441\u043E\
        \u0431\u0440\u0430\u0442\u044C \u043C\u0435\u0442\u0440\u0438\u043A\u0438\
        \ Polling Service \u0431\u043E\u043B\u0435\u0435 2 \u043C\u0438\u043D\u0443\
        \u0442."
  - alert: InfraScopeWorkerDown
    expr: max_over_time(up{job="infrascope-worker"}[2m]) == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Worker \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\u0435\u043D"
      description: "Prometheus \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u0441\u043E\
        \u0431\u0440\u0430\u0442\u044C \u043C\u0435\u0442\u0440\u0438\u043A\u0438\
        \ Worker \u0431\u043E\u043B\u0435\u0435 2 \u043C\u0438\u043D\u0443\u0442."
