service:
  name: discovery-service
  port: 8012
  healthPath: /health
  metricsPath: /metrics
image:
  repository: ghcr.io/golubchikovkirill/sitegka-discovery-service
  tag: latest
replicaCount: 1
ingress:
  enabled: false
