service:
  name: network-control-service
  port: 8013
  healthPath: /health
  metricsPath: /metrics
image:
  repository: ghcr.io/golubchikovkirill/sitegka-network-control-service
  tag: latest
replicaCount: 1
ingress:
  enabled: false
