service:
  name: polling-service
  port: 8011
  healthPath: /health
  metricsPath: /metrics
image:
  repository: ghcr.io/golubchikovkirill/sitegka-polling-service
  tag: latest
replicaCount: 1
ingress:
  enabled: false
